insert into Locais(idLocal,idAcidente,municipio) values(1,1,'Agudo');
insert into Locais(idLocal,idAcidente,municipio) values(2,2,'Ajuricaba');
insert into Locais(idLocal,idAcidente,municipio) values(3,3,'Alegrete');
insert into Locais(idLocal,idAcidente,municipio) values(4,4,'Alegria');
insert into Locais(idLocal,idAcidente,municipio) values(5,5,'Almirante Tamandaré do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(6,6,'Alto Alegre');
insert into Locais(idLocal,idAcidente,municipio) values(7,7,'Alvorada');
insert into Locais(idLocal,idAcidente,municipio) values(8,8,'Amaral Ferrador');
insert into Locais(idLocal,idAcidente,municipio) values(9,9,'Anta Gorda');
insert into Locais(idLocal,idAcidente,municipio) values(10,10,'Antônio Prado');
insert into Locais(idLocal,idAcidente,municipio) values(11,11,'Araricá');
insert into Locais(idLocal,idAcidente,municipio) values(12,12,'Aratiba');
insert into Locais(idLocal,idAcidente,municipio) values(13,13,'Arroio do Meio');
insert into Locais(idLocal,idAcidente,municipio) values(14,14,'Arroio do Padre');
insert into Locais(idLocal,idAcidente,municipio) values(15,15,'Arroio do Sal');
insert into Locais(idLocal,idAcidente,municipio) values(16,16,'Arroio do Tigre');
insert into Locais(idLocal,idAcidente,municipio) values(17,17,'Arroio dos Ratos');
insert into Locais(idLocal,idAcidente,municipio) values(18,18,'Arroio Grande');
insert into Locais(idLocal,idAcidente,municipio) values(19,19,'Arvorezinha');
insert into Locais(idLocal,idAcidente,municipio) values(20,20,'Áurea');
insert into Locais(idLocal,idAcidente,municipio) values(21,21,'Bagé');
insert into Locais(idLocal,idAcidente,municipio) values(22,22,'Balneário Pinhal');
insert into Locais(idLocal,idAcidente,municipio) values(23,23,'Barão');
insert into Locais(idLocal,idAcidente,municipio) values(24,24,'Barão de Cotegipe');
insert into Locais(idLocal,idAcidente,municipio) values(25,25,'Barra do Guarita');
insert into Locais(idLocal,idAcidente,municipio) values(26,26,'Barra do Ribeiro');
insert into Locais(idLocal,idAcidente,municipio) values(27,27,'Barra Funda');
insert into Locais(idLocal,idAcidente,municipio) values(28,28,'Barracão');
insert into Locais(idLocal,idAcidente,municipio) values(29,29,'Barros Cassal');
insert into Locais(idLocal,idAcidente,municipio) values(30,30,'Bento Gonçalves');
insert into Locais(idLocal,idAcidente,municipio) values(31,31,'Boa Vista das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(32,32,'Boa Vista do Buricá');
insert into Locais(idLocal,idAcidente,municipio) values(33,33,'Bom Jesus');
insert into Locais(idLocal,idAcidente,municipio) values(34,34,'Bom Princípio');
insert into Locais(idLocal,idAcidente,municipio) values(35,35,'Bom Progresso');
insert into Locais(idLocal,idAcidente,municipio) values(36,36,'Bom Retiro do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(37,37,'Boqueirão do Leão');
insert into Locais(idLocal,idAcidente,municipio) values(38,38,'Bossoroca');
insert into Locais(idLocal,idAcidente,municipio) values(39,39,'Brochier');
insert into Locais(idLocal,idAcidente,municipio) values(40,40,'Butiá');
insert into Locais(idLocal,idAcidente,municipio) values(41,41,'Caçapava do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(42,42,'Cacequi');
insert into Locais(idLocal,idAcidente,municipio) values(43,43,'Cachoeira do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(44,44,'Cachoeirinha');
insert into Locais(idLocal,idAcidente,municipio) values(45,45,'Cacique Doble');
insert into Locais(idLocal,idAcidente,municipio) values(46,46,'Caibaté');
insert into Locais(idLocal,idAcidente,municipio) values(47,47,'Camaquã');
insert into Locais(idLocal,idAcidente,municipio) values(48,48,'Camargo');
insert into Locais(idLocal,idAcidente,municipio) values(49,49,'Campestre da Serra');
insert into Locais(idLocal,idAcidente,municipio) values(50,50,'Campo Bom');
insert into Locais(idLocal,idAcidente,municipio) values(51,51,'Campos Borges');
insert into Locais(idLocal,idAcidente,municipio) values(52,52,'Candelária');
insert into Locais(idLocal,idAcidente,municipio) values(53,53,'Cândido Godói');
insert into Locais(idLocal,idAcidente,municipio) values(54,54,'Candiota');
insert into Locais(idLocal,idAcidente,municipio) values(55,55,'Canela');
insert into Locais(idLocal,idAcidente,municipio) values(56,56,'Canguçu');
insert into Locais(idLocal,idAcidente,municipio) values(57,57,'Canoas');
insert into Locais(idLocal,idAcidente,municipio) values(58,58,'Capão Bonito do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(59,59,'Capão da Canoa');
insert into Locais(idLocal,idAcidente,municipio) values(60,60,'Capão do Leão');
insert into Locais(idLocal,idAcidente,municipio) values(61,61,'Capela de Santana');
insert into Locais(idLocal,idAcidente,municipio) values(62,62,'Capivari do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(63,63,'Carazinho');
insert into Locais(idLocal,idAcidente,municipio) values(64,64,'Carlos Barbosa');
insert into Locais(idLocal,idAcidente,municipio) values(65,65,'Casca');
insert into Locais(idLocal,idAcidente,municipio) values(66,66,'Caseiros');
insert into Locais(idLocal,idAcidente,municipio) values(67,67,'Catuípe');
insert into Locais(idLocal,idAcidente,municipio) values(68,68,'Caxias do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(69,69,'Cerrito');
insert into Locais(idLocal,idAcidente,municipio) values(70,70,'Cerro Branco');
insert into Locais(idLocal,idAcidente,municipio) values(71,71,'Cerro Grande');
insert into Locais(idLocal,idAcidente,municipio) values(72,72,'Cerro Grande do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(73,73,'Chapada');
insert into Locais(idLocal,idAcidente,municipio) values(74,74,'Charqueadas');
insert into Locais(idLocal,idAcidente,municipio) values(75,75,'Cidreira');
insert into Locais(idLocal,idAcidente,municipio) values(76,76,'Ciríaco');
insert into Locais(idLocal,idAcidente,municipio) values(77,77,'Coronel Bicaco');
insert into Locais(idLocal,idAcidente,municipio) values(78,78,'Coxilha');
insert into Locais(idLocal,idAcidente,municipio) values(79,79,'Cristal');
insert into Locais(idLocal,idAcidente,municipio) values(80,80,'Cristal do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(81,81,'Cruz Alta');
insert into Locais(idLocal,idAcidente,municipio) values(82,82,'Cruzaltense');
insert into Locais(idLocal,idAcidente,municipio) values(83,83,'Cruzeiro do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(84,84,'David Canabarro');
insert into Locais(idLocal,idAcidente,municipio) values(85,85,'Dezesseis de Novembro');
insert into Locais(idLocal,idAcidente,municipio) values(86,86,'Dois Irmãos');
insert into Locais(idLocal,idAcidente,municipio) values(87,87,'Dois Lajeados');
insert into Locais(idLocal,idAcidente,municipio) values(88,88,'Dom Feliciano');
insert into Locais(idLocal,idAcidente,municipio) values(89,89,'Dom Pedrito');
insert into Locais(idLocal,idAcidente,municipio) values(90,90,'Doutor Maurício Cardoso');
insert into Locais(idLocal,idAcidente,municipio) values(91,91,'Doutor Ricardo');
insert into Locais(idLocal,idAcidente,municipio) values(92,92,'Eldorado do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(93,93,'Encantado');
insert into Locais(idLocal,idAcidente,municipio) values(94,94,'Encruzilhada do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(95,95,'Entre-Ijuís');
insert into Locais(idLocal,idAcidente,municipio) values(96,96,'Erechim');
insert into Locais(idLocal,idAcidente,municipio) values(97,97,'Ernestina');
insert into Locais(idLocal,idAcidente,municipio) values(98,98,'Erval Grande');
insert into Locais(idLocal,idAcidente,municipio) values(99,99,'Esmeralda');
insert into Locais(idLocal,idAcidente,municipio) values(100,100,'Espumoso');
insert into Locais(idLocal,idAcidente,municipio) values(101,101,'Estação');
insert into Locais(idLocal,idAcidente,municipio) values(102,102,'Estância Velha');
insert into Locais(idLocal,idAcidente,municipio) values(103,103,'Esteio');
insert into Locais(idLocal,idAcidente,municipio) values(104,104,'Estrela');
insert into Locais(idLocal,idAcidente,municipio) values(105,105,'Estrela Velha');
insert into Locais(idLocal,idAcidente,municipio) values(106,106,'Eugênio de Castro');
insert into Locais(idLocal,idAcidente,municipio) values(107,107,'Farroupilha');
insert into Locais(idLocal,idAcidente,municipio) values(108,108,'Faxinal do Soturno');
insert into Locais(idLocal,idAcidente,municipio) values(109,109,'Fazenda Vilanova');
insert into Locais(idLocal,idAcidente,municipio) values(110,110,'Feliz');
insert into Locais(idLocal,idAcidente,municipio) values(111,111,'Flores da Cunha');
insert into Locais(idLocal,idAcidente,municipio) values(112,112,'Fontoura Xavier');
insert into Locais(idLocal,idAcidente,municipio) values(113,113,'Formigueiro');
insert into Locais(idLocal,idAcidente,municipio) values(114,114,'Fortaleza dos Valos');
insert into Locais(idLocal,idAcidente,municipio) values(115,115,'Frederico Westphalen');
insert into Locais(idLocal,idAcidente,municipio) values(116,116,'Garibaldi');
insert into Locais(idLocal,idAcidente,municipio) values(117,117,'Gaurama');
insert into Locais(idLocal,idAcidente,municipio) values(118,118,'General Câmara');
insert into Locais(idLocal,idAcidente,municipio) values(119,119,'Gentil');
insert into Locais(idLocal,idAcidente,municipio) values(120,120,'Getúlio Vargas');
insert into Locais(idLocal,idAcidente,municipio) values(121,121,'Giruá');
insert into Locais(idLocal,idAcidente,municipio) values(122,122,'Glorinha');
insert into Locais(idLocal,idAcidente,municipio) values(123,123,'Gramado');
insert into Locais(idLocal,idAcidente,municipio) values(124,124,'Gramado dos Loureiros');
insert into Locais(idLocal,idAcidente,municipio) values(125,125,'Gramado Xavier');
insert into Locais(idLocal,idAcidente,municipio) values(126,126,'Gravataí');
insert into Locais(idLocal,idAcidente,municipio) values(127,127,'Guaíba');
insert into Locais(idLocal,idAcidente,municipio) values(128,128,'Guaporé');
insert into Locais(idLocal,idAcidente,municipio) values(129,129,'Guarani das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(130,130,'Harmonia');
insert into Locais(idLocal,idAcidente,municipio) values(131,131,'Herval');
insert into Locais(idLocal,idAcidente,municipio) values(132,132,'Herveiras');
insert into Locais(idLocal,idAcidente,municipio) values(133,133,'Horizontina');
insert into Locais(idLocal,idAcidente,municipio) values(134,134,'Hulha Negra');
insert into Locais(idLocal,idAcidente,municipio) values(135,135,'Ibiaçá');
insert into Locais(idLocal,idAcidente,municipio) values(136,136,'Ibiraiaras');
insert into Locais(idLocal,idAcidente,municipio) values(137,137,'Ibirubá');
insert into Locais(idLocal,idAcidente,municipio) values(138,138,'Igrejinha');
insert into Locais(idLocal,idAcidente,municipio) values(139,139,'Ijuí');
insert into Locais(idLocal,idAcidente,municipio) values(140,140,'Imigrante');
insert into Locais(idLocal,idAcidente,municipio) values(141,141,'Independência');
insert into Locais(idLocal,idAcidente,municipio) values(142,142,'Ipê');
insert into Locais(idLocal,idAcidente,municipio) values(143,143,'Ipiranga do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(144,144,'Iraí');
insert into Locais(idLocal,idAcidente,municipio) values(145,145,'Itaara');
insert into Locais(idLocal,idAcidente,municipio) values(146,146,'Itaqui');
insert into Locais(idLocal,idAcidente,municipio) values(147,147,'Itati');
insert into Locais(idLocal,idAcidente,municipio) values(148,148,'Ivoti');
insert into Locais(idLocal,idAcidente,municipio) values(149,149,'Jaboticaba');
insert into Locais(idLocal,idAcidente,municipio) values(150,150,'Jaguarão');
insert into Locais(idLocal,idAcidente,municipio) values(151,151,'Jaguari');
insert into Locais(idLocal,idAcidente,municipio) values(152,152,'Júlio de Castilhos');
insert into Locais(idLocal,idAcidente,municipio) values(153,153,'Lagoa dos Três Cantos');
insert into Locais(idLocal,idAcidente,municipio) values(154,154,'LAGOA VERMELHO');
insert into Locais(idLocal,idAcidente,municipio) values(155,155,'Lajeado');
insert into Locais(idLocal,idAcidente,municipio) values(156,156,'Lavras do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(157,157,'Liberato Salzano');
insert into Locais(idLocal,idAcidente,municipio) values(158,158,'Lindolfo Collor');
insert into Locais(idLocal,idAcidente,municipio) values(159,159,'Maçambará');
insert into Locais(idLocal,idAcidente,municipio) values(160,160,'Maquiné');
insert into Locais(idLocal,idAcidente,municipio) values(161,161,'Marau');
insert into Locais(idLocal,idAcidente,municipio) values(162,162,'Mariana Pimentel');
insert into Locais(idLocal,idAcidente,municipio) values(163,163,'Marques de Souza');
insert into Locais(idLocal,idAcidente,municipio) values(164,164,'Mata');
insert into Locais(idLocal,idAcidente,municipio) values(165,165,'Mato Castelhano');
insert into Locais(idLocal,idAcidente,municipio) values(166,166,'Maximiliano de Almeida');
insert into Locais(idLocal,idAcidente,municipio) values(167,167,'Miraguaí');
insert into Locais(idLocal,idAcidente,municipio) values(168,168,'Monte Alegre dos Campos');
insert into Locais(idLocal,idAcidente,municipio) values(169,169,'Montenegro');
insert into Locais(idLocal,idAcidente,municipio) values(170,170,'Morro Redondo');
insert into Locais(idLocal,idAcidente,municipio) values(171,171,'Morro Reuter');
insert into Locais(idLocal,idAcidente,municipio) values(172,172,'Muçum');
insert into Locais(idLocal,idAcidente,municipio) values(173,173,'Muitos Capões');
insert into Locais(idLocal,idAcidente,municipio) values(174,174,'Não-Me-Toque');
insert into Locais(idLocal,idAcidente,municipio) values(175,175,'Nicolau Vergueiro');
insert into Locais(idLocal,idAcidente,municipio) values(176,176,'Nonoai');
insert into Locais(idLocal,idAcidente,municipio) values(177,177,'Nova Araçá');
insert into Locais(idLocal,idAcidente,municipio) values(178,178,'Nova Petrópolis');
insert into Locais(idLocal,idAcidente,municipio) values(179,179,'Nova Prata');
insert into Locais(idLocal,idAcidente,municipio) values(180,180,'Nova Santa Rita');
insert into Locais(idLocal,idAcidente,municipio) values(181,181,'Novo Barreiro');
insert into Locais(idLocal,idAcidente,municipio) values(182,182,'Novo Cabrais');
insert into Locais(idLocal,idAcidente,municipio) values(183,183,'Novo Hamburgo');
insert into Locais(idLocal,idAcidente,municipio) values(184,184,'Osório');
insert into Locais(idLocal,idAcidente,municipio) values(185,185,'Palmares do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(186,186,'Palmeira das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(187,187,'Palmitinho');
insert into Locais(idLocal,idAcidente,municipio) values(188,188,'Panambi');
insert into Locais(idLocal,idAcidente,municipio) values(189,189,'Pantano Grande');
insert into Locais(idLocal,idAcidente,municipio) values(190,190,'Paraíso do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(191,191,'Parobé');
insert into Locais(idLocal,idAcidente,municipio) values(192,192,'Passa Sete');
insert into Locais(idLocal,idAcidente,municipio) values(193,193,'Passo Fundo');
insert into Locais(idLocal,idAcidente,municipio) values(194,194,'Paverama');
insert into Locais(idLocal,idAcidente,municipio) values(195,195,'Pelotas');
insert into Locais(idLocal,idAcidente,municipio) values(196,196,'Pinhal');
insert into Locais(idLocal,idAcidente,municipio) values(197,197,'Pinheiro Machado');
insert into Locais(idLocal,idAcidente,municipio) values(198,198,'Pinto Bandeira');
insert into Locais(idLocal,idAcidente,municipio) values(199,199,'Piratini');
insert into Locais(idLocal,idAcidente,municipio) values(200,200,'Planalto');
insert into Locais(idLocal,idAcidente,municipio) values(201,201,'Pontão');
insert into Locais(idLocal,idAcidente,municipio) values(202,202,'Portão');
insert into Locais(idLocal,idAcidente,municipio) values(203,203,'Porto Alegre');
insert into Locais(idLocal,idAcidente,municipio) values(204,204,'Porto Xavier');
insert into Locais(idLocal,idAcidente,municipio) values(205,205,'Pouso Novo');
insert into Locais(idLocal,idAcidente,municipio) values(206,206,'Quaraí');
insert into Locais(idLocal,idAcidente,municipio) values(207,207,'Quevedos');
insert into Locais(idLocal,idAcidente,municipio) values(208,208,'Redentora');
insert into Locais(idLocal,idAcidente,municipio) values(209,209,'Restinga Seca');
insert into Locais(idLocal,idAcidente,municipio) values(210,210,'Rio Grande');
insert into Locais(idLocal,idAcidente,municipio) values(211,211,'Rio Pardo');
insert into Locais(idLocal,idAcidente,municipio) values(212,212,'Roca Sales');
insert into Locais(idLocal,idAcidente,municipio) values(213,213,'Rolante');
insert into Locais(idLocal,idAcidente,municipio) values(214,214,'Ronda Alta');
insert into Locais(idLocal,idAcidente,municipio) values(215,215,'Rondinha');
insert into Locais(idLocal,idAcidente,municipio) values(216,216,'Roque Gonzales');
insert into Locais(idLocal,idAcidente,municipio) values(217,217,'Rosário do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(218,218,'Saldanha Marinho');
insert into Locais(idLocal,idAcidente,municipio) values(219,219,'Salto do Jacuí');
insert into Locais(idLocal,idAcidente,municipio) values(220,220,'Salvador do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(221,221,'Sananduva');
insert into Locais(idLocal,idAcidente,municipio) values(222,222,'Santa Bárbara do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(223,223,'Santa Cruz do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(224,224,'Santa Margarida do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(225,225,'Santa Maria');
insert into Locais(idLocal,idAcidente,municipio) values(226,226,'Santa Maria do Herval');
insert into Locais(idLocal,idAcidente,municipio) values(227,227,'Santa Rosa');
insert into Locais(idLocal,idAcidente,municipio) values(228,228,'Santa Vitória do Palmar');
insert into Locais(idLocal,idAcidente,municipio) values(229,229,'Santana do Livramento');
insert into Locais(idLocal,idAcidente,municipio) values(230,230,'Santiago');
insert into Locais(idLocal,idAcidente,municipio) values(231,231,'Santo Ângelo');
insert into Locais(idLocal,idAcidente,municipio) values(232,232,'Santo Antônio da Patrulha');
insert into Locais(idLocal,idAcidente,municipio) values(233,233,'Santo Antônio das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(234,234,'Santo Augusto');
insert into Locais(idLocal,idAcidente,municipio) values(235,235,'São Borja');
insert into Locais(idLocal,idAcidente,municipio) values(236,236,'São Domingos do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(237,237,'São Francisco de Assis');
insert into Locais(idLocal,idAcidente,municipio) values(238,238,'São Francisco de Paula');
insert into Locais(idLocal,idAcidente,municipio) values(239,239,'São Gabriel');
insert into Locais(idLocal,idAcidente,municipio) values(240,240,'São Jerônimo');
insert into Locais(idLocal,idAcidente,municipio) values(241,241,'São João do Polêsine');
insert into Locais(idLocal,idAcidente,municipio) values(242,242,'São José das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(243,243,'São José do Herval');
insert into Locais(idLocal,idAcidente,municipio) values(244,244,'São José do Hortêncio');
insert into Locais(idLocal,idAcidente,municipio) values(245,245,'São José do Norte');
insert into Locais(idLocal,idAcidente,municipio) values(246,246,'São José do Ouro');
insert into Locais(idLocal,idAcidente,municipio) values(247,247,'São José dos Ausentes');
insert into Locais(idLocal,idAcidente,municipio) values(248,248,'São Leopoldo');
insert into Locais(idLocal,idAcidente,municipio) values(249,249,'São Lourenço do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(250,250,'São Luiz Gonzaga');
insert into Locais(idLocal,idAcidente,municipio) values(251,251,'São Marcos');
insert into Locais(idLocal,idAcidente,municipio) values(252,252,'São Martinho');
insert into Locais(idLocal,idAcidente,municipio) values(253,253,'São Miguel das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(254,254,'São Pedro da Serra');
insert into Locais(idLocal,idAcidente,municipio) values(255,255,'São Pedro das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(256,256,'São Pedro do Butiá');
insert into Locais(idLocal,idAcidente,municipio) values(257,257,'São Pedro do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(258,258,'São Sebastião do Caí');
insert into Locais(idLocal,idAcidente,municipio) values(259,259,'São Sepé');
insert into Locais(idLocal,idAcidente,municipio) values(260,260,'São Vendelino');
insert into Locais(idLocal,idAcidente,municipio) values(261,261,'São Vicente do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(262,262,'Sapiranga');
insert into Locais(idLocal,idAcidente,municipio) values(263,263,'Sapucaia do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(264,264,'Sarandi');
insert into Locais(idLocal,idAcidente,municipio) values(265,265,'Seberi');
insert into Locais(idLocal,idAcidente,municipio) values(266,266,'Sede Nova');
insert into Locais(idLocal,idAcidente,municipio) values(267,267,'Selbach');
insert into Locais(idLocal,idAcidente,municipio) values(268,268,'Serafina Corrêa');
insert into Locais(idLocal,idAcidente,municipio) values(269,269,'Sertão');
insert into Locais(idLocal,idAcidente,municipio) values(270,270,'Sertão Santana');
insert into Locais(idLocal,idAcidente,municipio) values(271,271,'Sete de Setembro');
insert into Locais(idLocal,idAcidente,municipio) values(272,272,'Silveira Martins');
insert into Locais(idLocal,idAcidente,municipio) values(273,273,'Sinimbu');
insert into Locais(idLocal,idAcidente,municipio) values(274,274,'Sobradinho');
insert into Locais(idLocal,idAcidente,municipio) values(275,275,'Soledade');
insert into Locais(idLocal,idAcidente,municipio) values(276,276,'Tabaí');
insert into Locais(idLocal,idAcidente,municipio) values(277,277,'Tapejara');
insert into Locais(idLocal,idAcidente,municipio) values(278,278,'Tapera');
insert into Locais(idLocal,idAcidente,municipio) values(279,279,'Tapes');
insert into Locais(idLocal,idAcidente,municipio) values(280,280,'Taquara');
insert into Locais(idLocal,idAcidente,municipio) values(281,281,'Taquari');
insert into Locais(idLocal,idAcidente,municipio) values(282,282,'Taquaruçu do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(283,283,'Tenente Portela');
insert into Locais(idLocal,idAcidente,municipio) values(284,284,'Terra de Areia');
insert into Locais(idLocal,idAcidente,municipio) values(285,285,'Tio Hugo');
insert into Locais(idLocal,idAcidente,municipio) values(286,286,'Tiradentes do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(287,287,'Torres');
insert into Locais(idLocal,idAcidente,municipio) values(288,288,'Tramandaí');
insert into Locais(idLocal,idAcidente,municipio) values(289,289,'Três Arroios');
insert into Locais(idLocal,idAcidente,municipio) values(290,290,'Três Cachoeiras');
insert into Locais(idLocal,idAcidente,municipio) values(291,291,'Três Coroas');
insert into Locais(idLocal,idAcidente,municipio) values(292,292,'Três de Maio');
insert into Locais(idLocal,idAcidente,municipio) values(293,293,'Três Palmeiras');
insert into Locais(idLocal,idAcidente,municipio) values(294,294,'Três Passos');
insert into Locais(idLocal,idAcidente,municipio) values(295,295,'Trindade do Sul');
insert into Locais(idLocal,idAcidente,municipio) values(296,296,'Triunfo');
insert into Locais(idLocal,idAcidente,municipio) values(297,297,'Tucunduva');
insert into Locais(idLocal,idAcidente,municipio) values(298,298,'Tupanciretã');
insert into Locais(idLocal,idAcidente,municipio) values(299,299,'Tupandi');
insert into Locais(idLocal,idAcidente,municipio) values(300,300,'Tuparendi');
insert into Locais(idLocal,idAcidente,municipio) values(301,301,'Turuçu');
insert into Locais(idLocal,idAcidente,municipio) values(302,302,'Uruguaiana');
insert into Locais(idLocal,idAcidente,municipio) values(303,303,'Vacaria');
insert into Locais(idLocal,idAcidente,municipio) values(304,304,'Vale do Sol');
insert into Locais(idLocal,idAcidente,municipio) values(305,305,'Vale Real');
insert into Locais(idLocal,idAcidente,municipio) values(306,306,'Vale Verde');
insert into Locais(idLocal,idAcidente,municipio) values(307,307,'Venâncio Aires');
insert into Locais(idLocal,idAcidente,municipio) values(308,308,'Vera Cruz');
insert into Locais(idLocal,idAcidente,municipio) values(309,309,'Veranópolis');
insert into Locais(idLocal,idAcidente,municipio) values(310,310,'Viamão');
insert into Locais(idLocal,idAcidente,municipio) values(311,311,'Vicente Dutra');
insert into Locais(idLocal,idAcidente,municipio) values(312,312,'Victor Graeff');
insert into Locais(idLocal,idAcidente,municipio) values(313,313,'Vila Flores');
insert into Locais(idLocal,idAcidente,municipio) values(314,314,'Vila Lângaro');
insert into Locais(idLocal,idAcidente,municipio) values(315,315,'Vila Maria');
insert into Locais(idLocal,idAcidente,municipio) values(316,316,'Vista Alegre');
insert into Locais(idLocal,idAcidente,municipio) values(317,317,'Vista Gaúcha');
insert into Locais(idLocal,idAcidente,municipio) values(318,318,'Vitória das Missões');
insert into Locais(idLocal,idAcidente,municipio) values(319,319,'Westfália');
insert into Locais(idLocal,idAcidente,municipio) values(320,320,'Xangri-lá');